name: Update Awesome CS2

on:
  schedule:
    - cron: '7 0 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ closed ]

permissions:
  contents: write

concurrency:
  group: update-awesome-cs2
  cancel-in-progress: false

jobs:
  update:
    if: github.actor != 'github-actions[bot]' && (github.event_name != 'pull_request' || github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate README and data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -V
          python generator/generate.py

      - name: Commit and push changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md current.tag data/
          git commit -m "chore: update README and data"
          git push 